# GitHub Action: Push git subdirectory as branch
# Source: https://github.com/marketplace/actions/push-git-subdirectory-as-branch

name: Deploy to GitHub Pages
on:
  repository_dispatch:
    types:
      - trigger-renderbook-workflow
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: inst/examples/_book
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
